name: Lint CI

on:
  # push:
  #   branches:
  #     - master
  #     - master-qa
  pull_request:
    branches:
      - master-qa

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm ci
    - name: npm run lint
      run: npm run lint
